baseURL = 'https://sylvie3789.github.io/'
languageCode = 'zh-cn'  # Change to 'zh-cn' if appropriate
title = "秋茶庭"
theme = 'ananke'

[params]
  mainSections = ["posts"]
  featured_image = "images/gohugo-default-sample-hero-image.jpg"
  env = "production"

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
